# 3.9 is a predefined Compose file format version that defines
# how a docker-compose.yml should be structured and what features are allowed.
---
version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: aws-eks-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=true
    networks:
      - aws-eks
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    container_name: aws-eks-frontend
    ports:
      - "8000:80"
    environment:
      - DEBUG=true
    networks:
      - aws-eks
    depends_on:
      - backend
    restart: unless-stopped
networks:
  aws-eks:
    driver: bridge
