---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend

spec:
  containers:
    - name: backend
      image: 831081046278.dkr.ecr.eu-north-1.amazonaws.com/backend:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 3000

      env:
        - name: DEBUG
          value: "true"

        - name: DATABASE_URL
          value: ""

        - name: JWT_SECRET
          value: ""
