apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend

spec:
  containers:
    - name: frontend
      image: 831081046278.dkr.ecr.eu-north-1.amazonaws.com/frontend:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: DEBUG
          value: "true"
