---
name: Build,push,deploy
on:
  push:
    branches:
      - main
concurrency:
  group: building the latest and canceling the remaining all.
  cancel-in-progress: true
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # setup buildx
      - name: Setting up docker buildx
        uses: docker/setup-buildx-action@v3
      # -----login ----------
      - name: login into Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # ------ build and push ----
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/aws-eks-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/aws-eks-backend:${{ github.sha }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/aws-eks-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/aws-eks-frontend:${{ github.sha }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend
